sudo: required
services:
  - docker

before_install:
  - docker build -t chakri1408/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chakri1408/react-test npm test

after_success:
  - docker build -t chakri1408/multi-client ./client
  - docker build -t chakri1408/multi-nginx ./ngnix
  - docker build -t chakri1408/multi-server ./server
  - docker build -t chakri1408/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push chakri1408/multi-client
  - docker push chakri1408/multi-nginx
  - docker push chakri1408/multi-server
  - docker push chakri1408/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-906099689075"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"